### ISSUE TITLE
在 右键 变量圆形块 时 如果空间不足 会 直接裁去右键菜单 超过变量圆形块的部分 并且 不给滚动条

### ISSUE THREAD

**Issue by Hi-awaBlack** [Clipteam/clipcc-gui#101]
### 描述一下bug
在 右键 变量圆形块 时 如果空间不足 会 直接裁去右键菜单 超过变量圆形块的部分 并且 不给滚动条
## 请叙述bug触发步骤
首先创建多个（最好是10个以上）的变量，然后将任意变量圆形块放在编辑界面上方，让其右键菜单无法完全显示，随后右键此变量圆形块。
## 预期的行为
将右键菜单移动到可完全显示的位置或添加滚动条
## 截图或视频
![](https://s3.bmp.ovh/imgs/2022/02/b2912dd85192bf9d.png)
## ClipCC版本
3.1.1-b202202081254

**Comment by SimonShiki** [comment]
原版也有这样的bug吗

**Comment by Hi-awaBlack** [comment]
> 原版也有这样的bug吗

原版给了滚动条

**Comment by SimonShiki** [comment]
已修复
