### ISSUE TITLE
函数内调用函数

### ISSUE THREAD

**Issue by FxmlesXD** [Clipteam/clipcc-gui#102]
### 描述一下bug
按照视频中的代码，网页会崩溃
（视频中的代码本身就有逻辑错误，应作出限制，例如函数内无法调用自身之类的。）
## 请叙述bug触发步骤
见视频
## 预期的行为
限制这种行为
## ClipCC版本

https://user-images.githubusercontent.com/79508714/154649309-0b4a9eb9-c9ca-4222-8070-d80de4b78c20.mp4

**Comment by SimonShiki** [comment]
你说的是对代码运行逻辑的检查吗
