### ISSUE TITLE
希望ClipCC添加以下功能

### ISSUE THREAD

**Issue by captainjht** [Clipteam/clipcc-gui#103]
我希望ClipCC能添加全局函数与返回值，添加更多字体，更新文字打印系统（现有的打印系统只能显示在最下层）

这能帮助我更好地开发作品

**Comment by SimonShiki** [comment]
返回值和全局函数已添加
打印字体可以自行设置
叠加层相关问题暂无计划，或许以后会以扩展的形式出现。

**Comment by captainjht** [comment]
好的，谢谢添加，希望ClipCC以后越做越大




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Simon ***@***.***&gt;; 
发送时间: 2022年2月20日(星期天) 上午6:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Clipteam/clipcc-gui] 希望ClipCC添加以下功能 (Issue #103)





 
返回值和全局函数已添加
 打印字体可以自行设置
 叠加层相关问题暂无计划，或许以后会以扩展的形式出现。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sparrowhe** [comment]
好耶

**Comment by SimonShiki** [comment]
好耶
