### ISSUE TITLE
调用功能设想

### ISSUE THREAD

**Issue by libaihaiyes** [Clipteam/clipcc-gui#111]
### 简述
 添加一个调用功能，可以在1个cc3文件中使用另一个cc3文件的代码（积木块）
### 为什么
为什么，额，挺难回答。提出这个设想完全是因为玩了一款游戏后心中一直在想怎么模块化，如果在cilpcc中添加此功能，那么我可以把人物的移动，跳跃，行为都做成一个cc3，直接在主体中调用，看起来很美，不是吗。
### 细节
首先，是怎么表示，可以像“函数”选项里的积木块一样：
——————————
|                               
|调用（xxxxxxxxxx）  
|                               
——————————
“xxxxxxxx”可以做成一个跟“当接收到信息xx”一样的圆形可展开列表，我也不知道怎么描述，但是你们可以去我说的积木看一看。展开列表后，可以添加一个路径，当开始后就运行那个文件。运行方式我目前有两种想法：第一，将代码复制过来，在这个程序上运行。第二，单开一个隐藏程序运行文件，然后把输出展现在舞台上。
其实本质上，这个调用功能就是一个加强（削弱？）版的函数块，所以不加此功能也无伤大雅

**Comment by SimonShiki** [comment]
很难说...因为单从实现难度来看，要改的东西挺多；而且单从描述来看，你需要的也不是“跨文件加载”这种东西。

把人物的移动，跳跃，行为都做成一个cc3，直接在主体中调用，那就相当于是在另外一个角色上执行脚本。这样的话，你需要的应该是一个能在运行过程中切换脚本作用域（即执行角色）的方法。

至于跨文件加载，抛开实现难度不谈，我认为除了在文件大小无法接受的情况下都能通过 ClipCC 的“全局自定义积木”功能解决。而在文件大小过大的情况下也仅仅是增加一个“从外部加载资源”的功能而已。

**Comment by libaihaiyes** [comment]
谢谢。其实当时只是头脑一热，写下了issue，看完你的邮件后也觉得直接用全局函数更好，现在我先去把那个issue关了先



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Clipteam/clipcc-gui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月24日(星期四) 上午7:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Clipteam/clipcc-gui] 调用功能设想 (Issue #111)





 
很难说...因为单从实现难度来看，要改的东西挺多；而且单从描述来看，你需要的也不是“跨文件加载”这种东西。
 
把人物的移动，跳跃，行为都做成一个cc3，直接在主体中调用，那就相当于是在另外一个角色上执行脚本。这样的话，你需要的应该是一个能在运行过程中切换脚本作用域（即执行角色）的方法。
 
至于跨文件加载，抛开实现难度不谈，我认为除了在文件大小无法接受的情况下都能通过 ClipCC 的“全局自定义积木”功能解决。而在文件大小过大的情况下也仅仅是增加一个“从外部加载资源”的功能而已。
