### ISSUE TITLE
列表名称显示为左对齐

### ISSUE THREAD

**Issue by KingAgain** [Clipteam/clipcc-gui#112]
### 描述一下bug
列表名称显示为左对齐

## 请叙述bug触发步骤
建立一个名称不多于两个字符的列表

## 预期的行为
列表名称显示为居中

## 截图或视频
![image](https://user-images.githubusercontent.com/97130830/160549370-bf925886-0be8-4501-b39b-9aebb5064e52.png)

## ClipCC版本
社区预览版、稳定版及金丝雀开发版

## 附加内容
无

**Comment by SimonShiki** [comment]
原版经测试也存在相同问题
![image](https://user-images.githubusercontent.com/59327348/160549882-2c172c60-e29d-4548-a581-092368d6bbcd.png)

**Comment by alexcui03** [comment]
又要帮llk修bug 麻了

**Comment by sparrowhe** [comment]
已修复

Ref: https://github.com/Clipteam/clipcc-block/commit/f15b47463032896807f12da0a906e926c07cc4c0
