### ISSUE TITLE
侦测模块“a的x”将公有变量视为舞台的私有变量

### ISSUE THREAD

**Issue by KingAgain** [Clipteam/clipcc-gui#113]
### 描述一下bug
侦测模块“a的x”（如 舞台的背景编号）将公有变量视为舞台的私有变量

## 请叙述bug触发步骤
建立公有变量“c”，拖拽出“a的x”，并将a设为舞台，发现x可设为“c”

## 预期的行为
x不可设为“c”

## 截图或视频
![image](https://user-images.githubusercontent.com/97130830/160550825-2a68f3e6-7baa-4b10-b593-cbd3e238af48.png)

## ClipCC版本
社区预览版、稳定版及金丝雀预览版。

## 附加内容
无

**Comment by SimonShiki** [comment]
按照原有 Scratch 的逻辑，VM 会将公有变量在一定情况下视为舞台的私有变量。任何编辑器都不应该破坏原始 Scratch 的运行逻辑并使其破坏对原有程序的兼容性

**Comment by alexcui03** [comment]
舞台的私有变量即为全局变量 这是同一个东西 sc把舞台认为是除了自定义模块外的一个全局环境
