### ISSUE TITLE
将“字符串s1中s2第a次出现位置”模块中 s2设为单字符且a不为1时 无法正确返回结果

### ISSUE THREAD

**Issue by KingAgain** [Clipteam/clipcc-gui#114]
### 描述一下bug
将“字符串s1中s2第a次出现位置”模块中 s2设为单字符后无法正确返回结果

## 请叙述bug触发步骤
将“字符串s1中s2第a次出现位置”模块中 s1设为“ClipCC”s2设为“C”a设为“3”
## 预期的行为
返回正确结果

## 截图或视频
![image](https://user-images.githubusercontent.com/97130830/160553417-a1de1f68-f773-4483-ae34-14f768bed2a6.png)

## ClipCC版本
社区预览版、稳定版及金丝雀版

## 附加内容
无

**Comment by SimonShiki** [comment]
已修复
