### ISSUE TITLE
打开带有扩展的 Scratch 文件时，在扩展管理中显示未勾选

### ISSUE THREAD

**Issue by Hi-awaBlack** [Clipteam/clipcc-gui#118]
### 描述一下bug
打开带有扩展的 Scratch 文件时，在扩展管理中显示未勾选，而在编辑页和积木栏中存在此扩展。
## 请叙述bug触发步骤
重新启动 ClipCC ，并在扩展管理中添加一个 HTTP IO 扩展，并从积木栏拖到编辑页，再保存到 Scratch 文件中（cc3或sb3均可），随后关闭 ClipCC。
双击此 Scratch 文件，并使用 ClipCC 打开（请勿直接在 ClipCC 中打开），再打开扩展管理，此时 HTTP IO 扩展显示未勾选。
## 预期的行为
打开带有扩展的 Scratch 文件时，在扩展管理中勾选。
## 截图或视频
https://cloud.06dn.com/s/AOdATg
(请下载查看视频)
## ClipCC版本
ClipCC Releases 3.1.1
## 附加内容
-

**Comment by SimonShiki** [comment]
Fixed
