### ISSUE TITLE
请求新功能:HD图片上传

### ISSUE THREAD

**Issue by xy-cloud-cn** [Clipteam/clipcc-gui#126]
我需要一个自动把上传的png,jpg等格式的图片自动转为svg矢量图的功能，类似于TW的HD image uploads
> Adds a new button above the "upload costume" button that automatically converts uploaded bitmap images into SVG (vector) images to avoid losing quality.
> Avoid using the HD upload button if you plan to edit the image after uploading.

在“上传图像”按钮上方添加一个新按钮，自动将上传的位图图像转换为SVG（矢量）图像，以避免丢失质量。
如果你打算在上传后编辑图像，请避免使用HD upload按钮。

但我并不需要编辑（）

同时呢，拖动图片进入时可以选择HD或者普通
感谢
`qwq~`

**Comment by SimonShiki** [comment]
我偏向于做成扩展来实现，总之先记下了
