### ISSUE TITLE
安全等级限制

### ISSUE THREAD

**Issue by cxzlw** [Clipteam/clipcc-gui#13]
用户可以选择自己的安全等级：
安全
普通
正常
风险
危险！！！（隐藏选项）
离线版的话可以有五个等级，最后一个等级要在风险下看得见，要打开需抄写危险警告以及用户协议
在线版的风险操作步骤为离线版的危险步骤，而危险不予提供，仅clip官方可允许他人打开
各大等级分级标准：
安全：scratch级别，无附加功能
普通：clipcc除去所有需授权功能
正常：允许运行scratchscript，需用户授权
风险：允许云数据，需用户授权
危险：全功能可用
授权建议：见此处

**Comment by Hydrostic** [comment]
无实际意义，但是感谢您的反馈
