### ISSUE TITLE
无法在第二个角色右边的状态栏里输入数字修改角色属性

### ISSUE THREAD

**Issue by filmtextbreakthexm** [Clipteam/clipcc-gui#132]
### 描述一下bug
若在第二个角色右边的状态栏里输入数字修改XY坐标，显示或隐藏，大小和方向，改了之后又会变回原来的数值，只能用积木来改

## 请叙述bug触发步骤
在第二个角色右边的状态栏里输入数字修改XY坐标，显示或隐藏，大小和方向的数值

## 预期的行为
若在第二个角色右边的状态栏里输入数字修改XY坐标，显示或隐藏，大小和方向，可以成功修改

## 截图或视频
没有

## ClipCC版本
金丝雀

## 附加内容
该状态栏的完整xpath：/html/body/div[1]/div/div[3]/div/div[2]/div[2]/div/div[1]/div[1]

**Comment by SimonShiki** [comment]
无法复现
