### ISSUE TITLE
动态创建变量

### ISSUE THREAD

**Issue by libaihaiyes** [Clipteam/clipcc-gui#139]
### 描述一下你想要的功能
可以用变量里的字符串创建变量等等,类似于:
=========
=创建变量()=
=========
=========
=删除变量()=
=========
### 你为什么想要实现它？（可选）
我最近在用clipcc实现自创语言,创建变量语句虽说可以用列表,但是动态创建,删除变量应该会更简洁,GE里有相关积木,做出来应该不难吧(dog)(dog)(dog)

**Comment by SimonShiki** [comment]
已采纳，将会以扩展的类型呈现

**Comment by libaihaiyes** [comment]
好的,谢谢

**Comment by SimonShiki** [comment]
先保留吧，等写完了再关

**Comment by SimonShiki** [comment]
已在转运酶扩展中实现
