### ISSUE TITLE
改进用户授权

### ISSUE THREAD

**Issue by cxzlw** [Clipteam/clipcc-gui#14]
程序可以有描述文件，可以在开始前描述权限并申请
在程序开始时还可以申请权限
然后只有用户允许的才可以运行否则失败
用户也可以选择单步执行，当需授权模块执行时弹出提示，进行[断点](https://github.com/Clipteam/clipcc-gui/issues/8)
程序可以调用申请并执行在执行时发起授权申请
用户在自己的设置（离线：编辑器设置，在线：个人设置）可以设置全局的白名单，避免审批麻烦
clipteam也可以在后台设置全局白名单来帮助用户授权（可以是免授权也可以是提示安全）

**Comment by Hydrostic** [comment]
ok
