### ISSUE TITLE
声音选项卡中删除所有声音会导致崩溃

### ISSUE THREAD

**Issue by SimonShiki** [Clipteam/clipcc-gui#141]
## 请叙述bug触发步骤
声音选项卡中删除所有声音会导致崩溃
## 预期的行为
声音选项卡中删除所有声音会导致崩溃
## 截图或视频
暂无
## ClipCC版本
3.1.3
## 附加内容
等待复现

**Comment by NanHaiJuRuo** [comment]
### 复现视频 见QQ群文件：
复现删除声音bug.mp4

**Comment by NanHaiJuRuo** [comment]
该问题已被修复。
