### ISSUE TITLE
空白造型名称行高异常

### ISSUE THREAD

**Issue by SimonShiki** [Clipteam/clipcc-gui#142]
### 描述一下bug
1 空白造型名称 、 背景名称 、 声音名称行高显示错误 ， 导致打钩位置也会错位 。
## 预期的行为
与原版一致
## 截图或视频
暂无
## ClipCC版本
3.1.3
## 附加内容
提供者：南蒟
本人未能准确复现

**Comment by alexcui03** [comment]
Fixed in Clipteam/clipcc-block@0e42025
