### ISSUE TITLE
希望实现数据库操作

### ISSUE THREAD

**Issue by OrdChaos** [Clipteam/clipcc-gui#146]
### 描述一下你想要的功能
希望实现一下数据库的操作，像是mysql的亦或是别的数据库的读写等等。
### 你为什么想要实现它？（可选）
更方便地搭建在线存档与跨平台服务......?

（赞助啦！希望clipcc越来越好！）
![image](https://user-images.githubusercontent.com/101442840/179884706-523ca116-906b-459e-8893-fe5d3e9bde14.png)

**Comment by SimonShiki** [comment]
感谢支持！MySQL的话我会未来找个时间看看的

**Comment by alexcui03** [comment]
这更应当使用扩展实现该功能

**Comment by SimonShiki** [comment]
> 这更应当使用扩展实现该功能

✓

**Comment by SimonShiki** [comment]
看了一下，网页不支持tcp连接，大概没法弄

**Comment by sparrowhe** [comment]
去掉大概 就是没法弄 可以close了
