### ISSUE TITLE
预览站Alert扩展建议

### ISSUE THREAD

**Issue by NanHaiJuRuo** [Clipteam/clipcc-gui#147]
### 弹出询问框 建议改为布尔值
询问框本身反馈的是布尔值，因此应当直接作为布尔值积木。

### 弹出输入框 建议能预先设置内部内容
输入框预先设置内部内容可以方便手动复制或修改对应内容。

**Comment by frank-782** [comment]
你应该去和扩展作者提意见，第三方扩展不在本仓库的处理范围内
