### ISSUE TITLE
原版扩展 makey makey 无法导入

### ISSUE THREAD

**Issue by NanHaiJuRuo** [Clipteam/clipcc-gui#148]
### 描述一下bug
该扩展为原版扩展，通常用于按下时重复触发，以及调试组合键触发。
## 请叙述bug触发步骤
如题，且无法使用角色导入。
## 预期的行为
原版有这个扩展。
## 截图或视频
**QQ群文件**  
导入角色时扩展不加载，导致makey无法导入.mp4
## ClipCC版本
在线版3.1.3、预览版3.1.3，离线版没试过。
## 附加内容
建议同时修复导入角色时不会自动加载扩展的问题。

**Comment by SimonShiki** [comment]
已修复
