### ISSUE TITLE
在线版3.1.3无法导入在线扩展

### ISSUE THREAD

**Issue by NanHaiJuRuo** [Clipteam/clipcc-gui#149]
### 描述一下bug
导入在线扩展时卡在 **安装中…** 的状态。
## 请叙述bug触发步骤
按照正常的获取扩展方式，打开**在线获取**，然后安装任意扩展。
## 预期的行为
正常获取。
## 截图或视频
暂无，如果不是我网络的问题就不需要。
## ClipCC版本
在线版3.1.3
## 附加内容
无

**Comment by SimonShiki** [comment]
该问题由扩展商店跨域引起。

**Comment by sparrowhe** [comment]
nginx配置修改后问题解决。
