### ISSUE TITLE
ClipCC 扩展语言重载后出现问题

### ISSUE THREAD

**Issue by SimonShiki** [Clipteam/clipcc-gui#152]
### 描述一下bug
ClipCC 扩展语言重载后出现问题
## 请叙述bug触发步骤
1. 加载一个包含多语言支持的 ClipCC 扩展
2. 选择一个与当前不同的语言
3. 看见错误
## 预期的行为
能够正常重载
## 截图或视频
![-558f1292d5f893eb.png](https://user-images.githubusercontent.com/59327348/180642322-998388b3-5496-4a4f-bec1-2295c4b27d2e.png)
## ClipCC版本
3.1.4 
## 附加内容
该问题伴随扩展 API 引入 branch 支持出现

**Comment by sparrowhe** [comment]
本问题可在canary版 b2a75aa 构建复现

**Comment by sparrowhe** [comment]
> 本问题可在canary版 [b2a75aa](https://github.com/Clipteam/clipcc-gui/commit/b2a75aa2fe2b2e0f7ee97531f3c7fc8c2e2e3bfb) 构建复现

另：当切换语言时编辑器窗口内有扩展模块，会导致模块丢失信息

**Comment by alexcui03** [comment]
fixed in clipteam/clipcc-vm@92923e8
