### ISSUE TITLE
插件更新后无法正常保存新版本

### ISSUE THREAD

**Issue by sparrowhe** [Clipteam/clipcc-gui#154]
### 描述一下bug

从扩展商店更新新版本插件后，保存作品然后重新打开仍为旧版插件

## 请叙述bug触发步骤

视频见附件

## 预期的行为

正常更新扩展

## 截图或视频

https://user-images.githubusercontent.com/26871028/180799410-6336a755-d3e3-4dc2-bd23-7206d148e7f0.mp4

## ClipCC版本

c3.1.3 其他未测试

## 附加内容

测试用作品 https://codingclip.com/editor/335

**Comment by SimonShiki** [comment]
已修复
