### ISSUE TITLE
JSON储存有转义字符时出现问题

### ISSUE THREAD

**Issue by sparrowhe** [Clipteam/clipcc-gui#156]
### 描述一下bug

如题，我不知道怎么描述，见下图。

![image](https://user-images.githubusercontent.com/26871028/180989965-7aa33809-dd9f-4a74-8cd7-0329ed5f93c1.png)
![image](https://user-images.githubusercontent.com/26871028/180989980-733d574f-7788-4b96-ab12-48e38c7556dd.png)
![image](https://user-images.githubusercontent.com/26871028/180989999-5572e823-542c-45b7-a4dd-4d045dcb4a42.png)
![CVQ76G)( C@YC ST CM%Q8C](https://user-images.githubusercontent.com/26871028/180990035-d00160d5-5b37-4968-93bf-02e70cb0f685.png)

## 请叙述bug触发步骤

想个办法让存进去的文件有相关字符即可

## 预期的行为

正常存取

## 截图或视频

见上方描述

## ClipCC版本

3.1.4 canary，其他未测试

## 附加内容

作品文件在qq群里有

**Comment by SimonShiki** [comment]
🥲

**Comment by SimonShiki** [comment]
该项功能需要更改 scratch-parser, 且有更简单的办法解决（扩展内）处理，因此暂不做考虑。
