### ISSUE TITLE
声音区新增声音后删所有声音会崩

### ISSUE THREAD

**Issue by NanHaiJuRuo** [Clipteam/clipcc-gui#158]
### 描述一下bug
虽然已修复删除自带声音导致的假报错，但是新增一个声音再删除还是会报错。
## 请叙述bug触发步骤
打开编辑器，进入声音区，删除声音。此时并没有出现报错，然而在下方添加随机声音后再次删除，报错出现。
## 预期的行为
正常删除但不会假报错
## 截图或视频
![image](https://user-images.githubusercontent.com/109646559/181183253-c3e78d96-77c7-469e-bbc6-f74edfb29327.png)
## ClipCC版本
![c3.1.3](https://user-images.githubusercontent.com/109646559/181183345-e1779730-c872-4ec0-9e2f-624d926996a4.png)

**Comment by SimonShiki** [comment]
独立版未发现此问题

**Comment by SimonShiki** [comment]
社区版仍未发现此问题
