### ISSUE TITLE
空格会播放声音（基于声音删除的bug）

### ISSUE THREAD

**Issue by NanHaiJuRuo** [Clipteam/clipcc-gui#159]
### 描述一下bug
该bug由awablack在群内提到，经本人实践成功复现。
## 请叙述bug触发步骤
自带声音删掉然后按空格，以及之后添加声音再按空格，然后删除声音再按空格。
## 预期的行为
原版不会这样。
## 截图或视频
QQ群文件 codingclip 声音bug.mp4
## ClipCC版本
c3.1.3

**Comment by SimonShiki** [comment]
删除后还会播放吗

**Comment by sparrowhe** [comment]
社区版可复现该问题，删除后仍会播放

https://user-images.githubusercontent.com/26871028/181676603-7fd3a076-deab-4d6f-bf83-0bbb54239d12.mp4

**Comment by sparrowhe** [comment]
> 社区版可复现该问题，删除后仍会播放
> 
>  1659065190359.mp4

Windows 10 19043.1826
Chrome 103.0.5060.134
