### ISSUE TITLE
Add support for data structures and algorithms

### ISSUE THREAD

**Issue by alexcui03** [Clipteam/clipcc-gui#16]
Add an extension which supports data structures and algorithms with a high efficiency.

**Comment by Eureka0225** [comment]
peach, you want play OI in scratch?

**Comment by alexcui03** [comment]
> peach, you want play OI in scratch?

why can't?

**Comment by Eureka0225** [comment]
> > peach, you want play OI in scratch?
> 
> why can't?

Scratch's run speed is too slow, most OI problem need bigger numbers, but bigger numbers will expend more times. It's not a good issue.

**Comment by alexcui03** [comment]
So you don’t use it? (smile)

Everyone who is learning algorithm all know it is unnecessary to choose which language they use, as it is less important than the algorithm itself, so why can’t? only speed? (smile)

MIND IS MORE THAN PROGRAM ITSELF

------------------------------------------
Alex Cui
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
