### ISSUE TITLE
作品#390加载1.2.1cvs扩展后创作页无法使用代码区

### ISSUE THREAD

**Issue by bddjr** [Clipteam/clipcc-gui#162]
### 描述一下bug
因为cvs的bug，反馈后Simon说回滚了，我加载新的cvs拖进去保存然后刷新就出问题了
## 请叙述bug触发步骤
（非原作者可改编作品后操作）进入[#390](//codingclip.com/editor/390)创作页，左下角加载扩展，在线扩展，安装canvas，启用canvas，退出，确定。然后把cvs中的任意积木拖到空白处，保存作品，刷新。
## 预期的行为
正常更换版本
## 截图或视频
![D07FGW8%%BPO{VFML$VQV(A](https://user-images.githubusercontent.com/109646559/181907781-a5bdb08f-c87f-4837-be80-5183f300ce65.png)

## ClipCC版本
c3.1.3

**Comment by SimonShiki** [comment]
待复现中

**Comment by SimonShiki** [comment]
请再次尝试
