### ISSUE TITLE
[Bug] 扩展添加的 monitor 没有正确显示其名称及颜色

### ISSUE THREAD

**Issue by alexcui03** [Clipteam/clipcc-gui#163]
## 错误描述
如下图所示, 扩展添加的 monitor 没有正确显示其名称(翻译)和颜色
![image](https://user-images.githubusercontent.com/30141313/181916627-4f7b5af4-aecf-4d42-bcd8-0991b6823238.png)

扩展模块原型
```javascript
{
    opcode: 'clipcc.test.reporterWithMonitor',
    type: type.BlockType.REPORTER,
    option: {
        monitor: true
    },
    messageId: 'clipcc.test.repoterWithMonitor',
    categoryId: 'clipcc.test.category',
    function: () => Number(new Date()) / 1000
}
```

## 预期行为
扩展的 monitor 应当使用与 reporter 模块一致的名称和颜色

## 版本
ClipCC 3.1.4-01a27c5-b202207290304 (canary)
Chrome 103.0.5060.134
Windows 11 10.0.22000.795

**Comment by sparrowhe** [comment]
已修复。
![image](https://user-images.githubusercontent.com/26871028/184054801-01cf1fd3-c106-4865-9986-799e50cadad4.png)
