### ISSUE TITLE
JSON 扩展对套娃 JSON 对象等的处理错误等

### ISSUE THREAD

**Issue by Hi-awaBlack** [Clipteam/clipcc-gui#166]
### 描述一下bug
这是"JSON"扩展对套娃 JSON 对象等的一个严重处理错误问题。  
#### 正确的
根据 JSON 语法，只有字符串才能加双引号，如下图所示：   
![image](https://user-images.githubusercontent.com/63138378/182543780-5da82c61-2678-432c-b6f0-8ab4d54c6e9a.png)
上图中，key1的值是一个对象，没有加双引号。  
key2的值是一个数组，也没有加双引号。
#### JSON扩展的
现在我们来到ClipCC中，新增"JSON"扩展，并尝试生成一个逻辑上与上图一致的JSON数组，积木块如下图所示：   
![image](https://user-images.githubusercontent.com/63138378/182544411-431d3373-dc11-4e35-93af-5a381c2de607.png)
运行结果：  
![image](https://user-images.githubusercontent.com/63138378/182544456-72de2bf5-7c2d-4cf4-b18c-e179b6a5c807.png)
您将发现key1的值中的对象和key2的值中的数组都被加了双引号，这是错误的，放入其他JSON校验平台中也是错误的。
这是由于在制作该扩展时未对内容做特判所导致的。
   
您还可发现出现了转义符，虽然只有一点，但是在多层JSON中这些转义符将指数增长，理论上这些转义符是不需要的。  
将这些转义符去掉并修改错误的引号后再放回ClipCC中进行读取，您会惊讶的发现他们仍可以被正确的读取。  
![image](https://user-images.githubusercontent.com/63138378/182545521-177b6ee0-3912-427f-9741-c1b827bf4006.png)
![image](https://user-images.githubusercontent.com/63138378/182545737-59897c19-ae66-4457-9b5b-e117aff9588e.png)
***
## 请叙述bug触发步骤
参见“描述一下bug”
## 预期的行为
正确对套娃 JSON 对象等进行处理
## 截图或视频
参见“描述一下bug”
## ClipCC版本
理论上的 ClipCC 3.0.0 Beat 1 至最新版本
## 附加内容
实际上我还希望在JSON扩展中添加一个积木块，关于这部分的内容将被移动至下一个Issue中。

**Comment by sparrowhe** [comment]
![image](https://user-images.githubusercontent.com/26871028/184266333-d2b71019-1713-4f73-9655-5fc966e7522d.png)
已修复
