### ISSUE TITLE
json扩展解析一行内容时将\n解析成空格

### ISSUE THREAD

**Issue by NanHaiJuRuo** [Clipteam/clipcc-gui#168]
### 描述一下bug
如题
## 请叙述bug触发步骤
如截图。
## 预期的行为
我认为应当按照一行内容完整解析出来。
## 截图或视频
<img width="156" alt="image" src="https://user-images.githubusercontent.com/109646559/182549473-f5260442-2c7f-49cc-b307-34b66508d2b1.png">

## ClipCC版本
c3.1.3（可能所有版都是这样）
## 附加内容
可能是特性，但是这并不方便去使用。

**Comment by sparrowhe** [comment]
已修复
