### ISSUE TITLE
整个导入扩展它不香吗Isn't make a expression importing delicious?

### ISSUE THREAD

**Issue by HeavySnowJakarta** [Clipteam/clipcc-gui#17]
像scratchx那样整个导入本地扩展的功能它不香吗，还可以像chrome一样整个网上应用店让用户做扩展传上去它不香吗？
Isn't making a importing local expressions like scratchx delicious?Isn't make a online expression store and let developers make expressions and upload it to the store delicious?

**Comment by SinanGentoo** [comment]
> 像scratchx那样整个导入本地扩展的功能它不香吗，还可以像chrome一样整个网上应用店让用户做扩展传上去它不香吗？
> Isn't making a importing local expressions like scratchx delicious?Isn't make a online expression store and let developers make expressions and upload it to the store delicious?

//todo

**Comment by Eureka0225** [comment]
But user's extensions may be do some bad things, so I think before upload user's extensions, administrators should review these extensions and choose accepcet or reject, like "pull requests" in github

**Comment by alexcui03** [comment]
it will be in progress next version

**Comment by SinanGentoo** [comment]
扩展功能正在制作中，详情请查看feature/extension分支。
