### ISSUE TITLE
移动设备中切换语言会导致卡顿

### ISSUE THREAD

**Issue by SimonShiki** [Clipteam/clipcc-gui#171]
## 请叙述bug触发步骤
在移动设备中切换语言，卡顿程度随语言切换次数的增多而增大。
## 预期的行为
与原版一致
## 截图或视频
暂无
## ClipCC版本
c 3.1.4
## 附加内容
本问题由切换语言后丢失 ref 引用而引起。

**Comment by alexcui03** [comment]
能否在pc复现

**Comment by SimonShiki** [comment]
> 能否在pc复现

否，表现为多组件 handleTouchEnd 提示 ref 丢失

**Comment by SimonShiki** [comment]
已修复
