### ISSUE TITLE
数组添加更多功能

### ISSUE THREAD

**Issue by NanHaiJuRuo** [Clipteam/clipcc-gui#173]
### 描述一下你想要的功能
既然现在的数组已经支持项的解析和项的修改，建议支持以下积木块

< (["测试","123456"]) 包含 (测试) ? >

( 在数组 (["测试","123456"]) 的第 (0) 项前插入 (哦哦哦) )
### 你为什么想要实现它？（可选）

**Comment by sparrowhe** [comment]
应到相应扩展的仓库下开issue

**Comment by NanHaiJuRuo** [comment]
> 应到相应扩展的仓库下开issue

这是JSON扩展，请问在哪发

**Comment by NanHaiJuRuo** [comment]
https://github.com/Clipteam/clipcc-vm/issues/56

**Comment by SimonShiki** [comment]
更多数组功能将会在未来以外部扩展的方式重新实现
