### ISSUE TITLE
加载scratch2ify扩展后积木颜色出现问题

### ISSUE THREAD

**Issue by lihl2011** [Clipteam/clipcc-gui#175]
### 描述一下bug
积木颜色出现问题

## 请叙述bug触发步骤
首先在扩展商店下载扩展“scratch2ify”，加入扩展，再关闭扩展，就会触发此bug
## 预期的行为
无
## 截图或视频
以函数模块为例：未加载前：
![未加载](https://s3.328888.xyz/2022/08/15/hNVOy.png)
加载后再移除：
![加载后再移除](https://s3.328888.xyz/2022/08/15/hNsKC.png)

## ClipCC版本
ClipCC所发行的包括此扩展的任何版本
## 附加内容
无

**Comment by SimonShiki** [comment]
扩展问题，不应由官方处理。
请前往扩展仓库提交 issue
