### ISSUE TITLE
作品页面没有60帧

### ISSUE THREAD

**Issue by awaBK2333** [Clipteam/clipcc-gui#179]
### 描述一下bug
作品发布后的页面里帧数没有60
## 请叙述bug触发步骤
打开任何一个作品运行即可发现（如 https://codingclip.com/project/602 ）
## 预期的行为
能够在运行时有60fps
## 截图或视频
https://user-images.githubusercontent.com/79268702/184853495-45ae68b1-13d3-4b6f-a0cf-efed3aac6d53.mp4
## ClipCC版本
在线版本（2022年8月16日）
## 附加内容
暂无

**Comment by NanHaiJuRuo** [comment]
经过我的测试，该bug属于未能保存fps参数，原作者在创作页内保存自定义帧数时，刷新后仍然30帧运行。

**Comment by SimonShiki** [comment]
已修复
