### ISSUE TITLE
JSON輸入被轉換到數字

### ISSUE THREAD

**Issue by Skyhigh173** [Clipteam/clipcc-gui#184]
### 描述一下bug

JSON輸入被轉換到數字,就算添加 `join(input)()`使其轉換到str也沒用

## 请叙述bug触发步骤
見圖

## 预期的行为
見圖, 應返回`{"key":"1e30000"}`
## 截图或视频
![image](https://user-images.githubusercontent.com/100467674/185931173-8f4a5b84-db5a-4c2a-9b79-e421dcb50aec.png)

## ClipCC版本
c3.1.4
## 附加内容

**Comment by SimonShiki** [comment]
又是一个修改问题呢

**Comment by SimonShiki** [comment]
已修复
