### ISSUE TITLE
切换语言后编辑器扩展启用状态丢失

### ISSUE THREAD

**Issue by SimonShiki** [Clipteam/clipcc-gui#187]
### 描述一下bug
切换语言后编辑器扩展启用状态丢失
## 预期的行为
1. 启用一个扩展(内置外置均可)
2. 切换语言
3. 再次打开扩展管理器，发现错误
## 截图或视频
https://user-images.githubusercontent.com/59327348/186616764-dfb550c5-d8ba-47b8-8f34-99f61f9f76ed.mp4
## ClipCC版本
3.1.4 金丝雀版
## 附加内容
暂无

**Comment by alexcui03** [comment]
fixed in Clipteam/clipcc-gui@8b9e347
