### ISSUE TITLE
部分积木前选择框状态问题(原版问题)及一个奇怪的报错问题(Clip CC问题)

### ISSUE THREAD

**Issue by Someone-Yang** [Clipteam/clipcc-gui#19]
# 更改

刚才跑去测试了下，在原生Scratch编辑器中也有几率出现这个问题，~~但不是Clip CC这样的100%出现这个问题~~ XD  
不过Clipteam有没有能力自主修复它呢？期待

---

~~虽然无伤大雅，但我还是提出来吧，毕竟他还报错了（害怕~~  
在点击“造型 编号/名称”和“背景 编号/名称”后可以正常在舞台显示值，但切换到“造型”或“声音”后再切换到“代码”时，积木的选择框被取消选中，但舞台上仍然正常显示。  
且在勾选后控制台有2个奇怪的错误输出。

# 触发步骤

![步骤1](https://s1.ax1x.com/2020/06/28/NRiZOU.jpg)  
首先在代码页点击相应积木前的选择框

![步骤2](https://s1.ax1x.com/2020/06/28/NRiVyT.th.jpg)  
然后转到造型/背景或音乐，此时舞台上仍然可以正常显示

![步骤3](https://s1.ax1x.com/2020/06/28/NRiElV.th.jpg)  
随后返回代码页，发现选择框已取消选中，但舞台上仍然可以正常显示

---

# 设备信息

Windows 7 x86,chromium 78.0.3904

**Comment by SinanGentoo** [comment]
能否给出具体报错信息？

**Comment by Someone-Yang** [comment]
> 能否给出具体报错信息？

```
lib.min.js.156979

Failed prop type: Invalid prop `monitors` of type `OrderedMap` supplied to `MonitorList`, expected instance of `OrderedMap`.
    in MonitorList (created by MonitorList)
    in MonitorList (created by Connect(MonitorList))
    in Connect(MonitorList) (created by InjectIntl(Connect(MonitorList)))
    in InjectIntl(Connect(MonitorList)) (created by ErrorBoundaryWrapper)
    in ErrorBoundary (created by Connect(ErrorBoundary))
    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
    in ErrorBoundaryWrapper (created by StageComponent)
    in div (created by Box)
    in Box (created by StageComponent)
    in div (created by Box)
    in Box (created by StageComponent)
    in div (created by StageComponent)
    in StageComponent (created by Stage)
    in Stage (created by Connect(Stage))
    in Connect(Stage) (created by StageWrapperComponent)
    in div (created by Box)
    in Box (created by StageWrapperComponent)
    in div (created by Box)
    in Box (created by StageWrapperComponent)
    in StageWrapperComponent (created by StageWrapper)
    in StageWrapper (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in MediaQuery (created by GUIComponent)
    in GUIComponent (created by Connect(GUIComponent))
    in Connect(GUIComponent) (created by InjectIntl(Connect(GUIComponent)))
    in InjectIntl(Connect(GUIComponent)) (created by GUI)
    in GUI (created by Connect(GUI))
    in Connect(GUI) (created by InjectIntl(Connect(GUI)))
    in InjectIntl(Connect(GUI)) (created by CloudManager)
    in CloudManager (created by Connect(CloudManager))
    in Connect(CloudManager) (created by VMManager)
    in VMManager (created by Connect(VMManager))
    in Connect(VMManager) (created by VMListener)
    in VMListener (created by Connect(VMListener))
    in Connect(VMListener) (created by ProjectSaverComponent)
    in ProjectSaverComponent (created by Connect(ProjectSaverComponent))
    in Connect(ProjectSaverComponent) (created by TitledComponent)
    in TitledComponent (created by Connect(TitledComponent))
    in Connect(TitledComponent) (created by InjectIntl(Connect(TitledComponent)))
    in InjectIntl(Connect(TitledComponent)) (created by ProjectFetcherComponent)
    in ProjectFetcherComponent (created by Connect(ProjectFetcherComponent))
    in Connect(ProjectFetcherComponent) (created by InjectIntl(Connect(ProjectFetcherComponent)))
    in InjectIntl(Connect(ProjectFetcherComponent)) (created by QueryParserComponent)
    in QueryParserComponent (created by Connect(QueryParserComponent))
    in Connect(QueryParserComponent) (created by FontLoaderComponent)
    in FontLoaderComponent (created by Connect(FontLoaderComponent))
    in Connect(FontLoaderComponent) (created by ErrorBoundaryWrapper)
    in ErrorBoundary (created by Connect(ErrorBoundary))
    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
    in ErrorBoundaryWrapper (created by LocalizationWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by LocalizationWrapper)
    in LocalizationWrapper (created by Connect(LocalizationWrapper))
    in Connect(LocalizationWrapper) (created by HashParserComponent)
    in HashParserComponent (created by Connect(HashParserComponent))
    in Connect(HashParserComponent) (created by AppStateWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by AppStateWrapper)
    in Provider (created by AppStateWrapper)
    in AppStateWrapper
```
```
lib.min.js.156979

Failed prop type: Invalid prop `children` supplied to `ContextMenuTrigger`, expected a ReactNode.
    in ContextMenuTrigger (created by MonitorComponent)
    in MonitorComponent (created by Monitor)
    in Monitor (created by Connect(Monitor))
    in Connect(Monitor) (created by InjectIntl(Connect(Monitor)))
    in InjectIntl(Connect(Monitor))
    in div (created by Box)
    in Box (created by MonitorList)
    in div (created by Box)
    in Box (created by MonitorList)
    in MonitorList (created by MonitorList)
    in MonitorList (created by Connect(MonitorList))
    in Connect(MonitorList) (created by InjectIntl(Connect(MonitorList)))
    in InjectIntl(Connect(MonitorList)) (created by ErrorBoundaryWrapper)
    in ErrorBoundary (created by Connect(ErrorBoundary))
    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
    in ErrorBoundaryWrapper (created by StageComponent)
    in div (created by Box)
    in Box (created by StageComponent)
    in div (created by Box)
    in Box (created by StageComponent)
    in div (created by StageComponent)
    in StageComponent (created by Stage)
    in Stage (created by Connect(Stage))
    in Connect(Stage) (created by StageWrapperComponent)
    in div (created by Box)
    in Box (created by StageWrapperComponent)
    in div (created by Box)
    in Box (created by StageWrapperComponent)
    in StageWrapperComponent (created by StageWrapper)
    in StageWrapper (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in MediaQuery (created by GUIComponent)
    in GUIComponent (created by Connect(GUIComponent))
    in Connect(GUIComponent) (created by InjectIntl(Connect(GUIComponent)))
    in InjectIntl(Connect(GUIComponent)) (created by GUI)
    in GUI (created by Connect(GUI))
    in Connect(GUI) (created by InjectIntl(Connect(GUI)))
    in InjectIntl(Connect(GUI)) (created by CloudManager)
    in CloudManager (created by Connect(CloudManager))
    in Connect(CloudManager) (created by VMManager)
    in VMManager (created by Connect(VMManager))
    in Connect(VMManager) (created by VMListener)
    in VMListener (created by Connect(VMListener))
    in Connect(VMListener) (created by ProjectSaverComponent)
    in ProjectSaverComponent (created by Connect(ProjectSaverComponent))
    in Connect(ProjectSaverComponent) (created by TitledComponent)
    in TitledComponent (created by Connect(TitledComponent))
    in Connect(TitledComponent) (created by InjectIntl(Connect(TitledComponent)))
    in InjectIntl(Connect(TitledComponent)) (created by ProjectFetcherComponent)
    in ProjectFetcherComponent (created by Connect(ProjectFetcherComponent))
    in Connect(ProjectFetcherComponent) (created by InjectIntl(Connect(ProjectFetcherComponent)))
    in InjectIntl(Connect(ProjectFetcherComponent)) (created by QueryParserComponent)
    in QueryParserComponent (created by Connect(QueryParserComponent))
    in Connect(QueryParserComponent) (created by FontLoaderComponent)
    in FontLoaderComponent (created by Connect(FontLoaderComponent))
    in Connect(FontLoaderComponent) (created by ErrorBoundaryWrapper)
    in ErrorBoundary (created by Connect(ErrorBoundary))
    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
    in ErrorBoundaryWrapper (created by LocalizationWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by LocalizationWrapper)
    in LocalizationWrapper (created by Connect(LocalizationWrapper))
    in Connect(LocalizationWrapper) (created by HashParserComponent)
    in HashParserComponent (created by Connect(HashParserComponent))
    in Connect(HashParserComponent) (created by AppStateWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by AppStateWrapper)
    in Provider (created by AppStateWrapper)
    in AppStateWrapper
```

**Comment by SinanGentoo** [comment]
> > 能否给出具体报错信息？
> 
> ```
> lib.min.js.156979
> 
> Failed prop type: Invalid prop `monitors` of type `OrderedMap` supplied to `MonitorList`, expected instance of `OrderedMap`.
>     in MonitorList (created by MonitorList)
>     in MonitorList (created by Connect(MonitorList))
>     in Connect(MonitorList) (created by InjectIntl(Connect(MonitorList)))
>     in InjectIntl(Connect(MonitorList)) (created by ErrorBoundaryWrapper)
>     in ErrorBoundary (created by Connect(ErrorBoundary))
>     in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
>     in ErrorBoundaryWrapper (created by StageComponent)
>     in div (created by Box)
>     in Box (created by StageComponent)
>     in div (created by Box)
>     in Box (created by StageComponent)
>     in div (created by StageComponent)
>     in StageComponent (created by Stage)
>     in Stage (created by Connect(Stage))
>     in Connect(Stage) (created by StageWrapperComponent)
>     in div (created by Box)
>     in Box (created by StageWrapperComponent)
>     in div (created by Box)
>     in Box (created by StageWrapperComponent)
>     in StageWrapperComponent (created by StageWrapper)
>     in StageWrapper (created by MediaQuery)
>     in div (created by Box)
>     in Box (created by MediaQuery)
>     in div (created by Box)
>     in Box (created by MediaQuery)
>     in div (created by Box)
>     in Box (created by MediaQuery)
>     in div (created by Box)
>     in Box (created by MediaQuery)
>     in MediaQuery (created by GUIComponent)
>     in GUIComponent (created by Connect(GUIComponent))
>     in Connect(GUIComponent) (created by InjectIntl(Connect(GUIComponent)))
>     in InjectIntl(Connect(GUIComponent)) (created by GUI)
>     in GUI (created by Connect(GUI))
>     in Connect(GUI) (created by InjectIntl(Connect(GUI)))
>     in InjectIntl(Connect(GUI)) (created by CloudManager)
>     in CloudManager (created by Connect(CloudManager))
>     in Connect(CloudManager) (created by VMManager)
>     in VMManager (created by Connect(VMManager))
>     in Connect(VMManager) (created by VMListener)
>     in VMListener (created by Connect(VMListener))
>     in Connect(VMListener) (created by ProjectSaverComponent)
>     in ProjectSaverComponent (created by Connect(ProjectSaverComponent))
>     in Connect(ProjectSaverComponent) (created by TitledComponent)
>     in TitledComponent (created by Connect(TitledComponent))
>     in Connect(TitledComponent) (created by InjectIntl(Connect(TitledComponent)))
>     in InjectIntl(Connect(TitledComponent)) (created by ProjectFetcherComponent)
>     in ProjectFetcherComponent (created by Connect(ProjectFetcherComponent))
>     in Connect(ProjectFetcherComponent) (created by InjectIntl(Connect(ProjectFetcherComponent)))
>     in InjectIntl(Connect(ProjectFetcherComponent)) (created by QueryParserComponent)
>     in QueryParserComponent (created by Connect(QueryParserComponent))
>     in Connect(QueryParserComponent) (created by FontLoaderComponent)
>     in FontLoaderComponent (created by Connect(FontLoaderComponent))
>     in Connect(FontLoaderComponent) (created by ErrorBoundaryWrapper)
>     in ErrorBoundary (created by Connect(ErrorBoundary))
>     in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
>     in ErrorBoundaryWrapper (created by LocalizationWrapper)
>     in IntlProvider (created by Connect(IntlProvider))
>     in Connect(IntlProvider) (created by LocalizationWrapper)
>     in LocalizationWrapper (created by Connect(LocalizationWrapper))
>     in Connect(LocalizationWrapper) (created by HashParserComponent)
>     in HashParserComponent (created by Connect(HashParserComponent))
>     in Connect(HashParserComponent) (created by AppStateWrapper)
>     in IntlProvider (created by Connect(IntlProvider))
>     in Connect(IntlProvider) (created by AppStateWrapper)
>     in Provider (created by AppStateWrapper)
>     in AppStateWrapper
> ```
> ```
> lib.min.js.156979
> 
> Failed prop type: Invalid prop `children` supplied to `ContextMenuTrigger`, expected a ReactNode.
>     in ContextMenuTrigger (created by MonitorComponent)
>     in MonitorComponent (created by Monitor)
>     in Monitor (created by Connect(Monitor))
>     in Connect(Monitor) (created by InjectIntl(Connect(Monitor)))
>     in InjectIntl(Connect(Monitor))
>     in div (created by Box)
>     in Box (created by MonitorList)
>     in div (created by Box)
>     in Box (created by MonitorList)
>     in MonitorList (created by MonitorList)
>     in MonitorList (created by Connect(MonitorList))
>     in Connect(MonitorList) (created by InjectIntl(Connect(MonitorList)))
>     in InjectIntl(Connect(MonitorList)) (created by ErrorBoundaryWrapper)
>     in ErrorBoundary (created by Connect(ErrorBoundary))
>     in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
>     in ErrorBoundaryWrapper (created by StageComponent)
>     in div (created by Box)
>     in Box (created by StageComponent)
>     in div (created by Box)
>     in Box (created by StageComponent)
>     in div (created by StageComponent)
>     in StageComponent (created by Stage)
>     in Stage (created by Connect(Stage))
>     in Connect(Stage) (created by StageWrapperComponent)
>     in div (created by Box)
>     in Box (created by StageWrapperComponent)
>     in div (created by Box)
>     in Box (created by StageWrapperComponent)
>     in StageWrapperComponent (created by StageWrapper)
>     in StageWrapper (created by MediaQuery)
>     in div (created by Box)
>     in Box (created by MediaQuery)
>     in div (created by Box)
>     in Box (created by MediaQuery)
>     in div (created by Box)
>     in Box (created by MediaQuery)
>     in div (created by Box)
>     in Box (created by MediaQuery)
>     in MediaQuery (created by GUIComponent)
>     in GUIComponent (created by Connect(GUIComponent))
>     in Connect(GUIComponent) (created by InjectIntl(Connect(GUIComponent)))
>     in InjectIntl(Connect(GUIComponent)) (created by GUI)
>     in GUI (created by Connect(GUI))
>     in Connect(GUI) (created by InjectIntl(Connect(GUI)))
>     in InjectIntl(Connect(GUI)) (created by CloudManager)
>     in CloudManager (created by Connect(CloudManager))
>     in Connect(CloudManager) (created by VMManager)
>     in VMManager (created by Connect(VMManager))
>     in Connect(VMManager) (created by VMListener)
>     in VMListener (created by Connect(VMListener))
>     in Connect(VMListener) (created by ProjectSaverComponent)
>     in ProjectSaverComponent (created by Connect(ProjectSaverComponent))
>     in Connect(ProjectSaverComponent) (created by TitledComponent)
>     in TitledComponent (created by Connect(TitledComponent))
>     in Connect(TitledComponent) (created by InjectIntl(Connect(TitledComponent)))
>     in InjectIntl(Connect(TitledComponent)) (created by ProjectFetcherComponent)
>     in ProjectFetcherComponent (created by Connect(ProjectFetcherComponent))
>     in Connect(ProjectFetcherComponent) (created by InjectIntl(Connect(ProjectFetcherComponent)))
>     in InjectIntl(Connect(ProjectFetcherComponent)) (created by QueryParserComponent)
>     in QueryParserComponent (created by Connect(QueryParserComponent))
>     in Connect(QueryParserComponent) (created by FontLoaderComponent)
>     in FontLoaderComponent (created by Connect(FontLoaderComponent))
>     in Connect(FontLoaderComponent) (created by ErrorBoundaryWrapper)
>     in ErrorBoundary (created by Connect(ErrorBoundary))
>     in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
>     in ErrorBoundaryWrapper (created by LocalizationWrapper)
>     in IntlProvider (created by Connect(IntlProvider))
>     in Connect(IntlProvider) (created by LocalizationWrapper)
>     in LocalizationWrapper (created by Connect(LocalizationWrapper))
>     in Connect(LocalizationWrapper) (created by HashParserComponent)
>     in HashParserComponent (created by Connect(HashParserComponent))
>     in Connect(HashParserComponent) (created by AppStateWrapper)
>     in IntlProvider (created by Connect(IntlProvider))
>     in Connect(IntlProvider) (created by AppStateWrapper)
>     in Provider (created by AppStateWrapper)
>     in AppStateWrapper
> ```

奇怪的问题...我之前调试也遇到过
总之 我会尝试修复的

**Comment by alexcui03** [comment]
我这里复现有点困难 大概率应该是block解析时候炸了

**Comment by Someone-Yang** [comment]
复现视频（手机演示）已上传：
https://b23.tv/oZgLSO

**Comment by SinanGentoo** [comment]
后者已修复
