### ISSUE TITLE
JSON 扩展对转义字符的转义

### ISSUE THREAD

**Issue by Hi-awaBlack** [Clipteam/clipcc-gui#191]
### 描述一下bug
ClipCC 自带扩展 JSON 对于转义字符（如`\n`或`\r`）的转义
## 请叙述bug触发步骤
![image](https://user-images.githubusercontent.com/63138378/189485077-8541ccac-2ef1-4c72-951b-d128791df020.png)
![image](https://user-images.githubusercontent.com/63138378/189485099-ede03cfc-39bc-4947-85b4-034fe59f98cc.png)

## 预期的行为
![image](https://user-images.githubusercontent.com/63138378/189485134-d23b82a7-7307-4ec0-b26d-a0f56dfdfb53.png)

对转义字符特判
## 截图或视频
同上
## ClipCC版本
3.1.4

**Comment by sparrowhe** [comment]
![image](https://user-images.githubusercontent.com/26871028/189523053-e4f9792a-c7e3-41d8-b602-6e34a65272a7.png)
Fixed

**Comment by NanHaiJuRuo** [comment]
考古
