### ISSUE TITLE
[建议]加速模式控制积木操作时应当更新舞台提示

### ISSUE THREAD

**Issue by Someone-Yang** [Clipteam/clipcc-gui#20]
如题。在使用加速模式控制积木开关加速模式时，开启/关闭加速模式后舞台上部分并未更新加速模式状态。建议在使用这些积木更改加速模式状态时同步更新舞台上方提示，不然用户将难以判断自己是否处于加速模式。  
同时，Shift + Green Flag的开关行为也应当跟随实时状态进行调整。

---

# 设备信息

Windows 7 x86,chromium 78.0.3904

**Comment by alexcui03** [comment]
已修复
[clipcc-vm#618d29c](https://github.com/Clipteam/clipcc-vm/commit/618d29cadf5a94fe32d666b47ac71aed10574212)
