### ISSUE TITLE
扩展搜索没法用

### ISSUE THREAD

**Issue by bddjr** [Clipteam/clipcc-gui#203]
### 描述一下bug
扩展管理的页面，搜索扩展后清空搜索框，其它已启用的扩展会变成未启用，然后退不出去了。
扩展商店页面用不了搜索。
## 预期的行为
正常使用两者的搜索功能。
## ClipCC版本
3.1.4

**Comment by NanHaiJuRuo** [comment]
![image](https://user-images.githubusercontent.com/109646559/192322070-9df26ab8-21e4-4a0a-b1cd-d216cecec7ee.png)
