### ISSUE TITLE
从已有标签页直接跳转到codingclip，会呈现未登录的状态

### ISSUE THREAD

**Issue by bddjr** [Clipteam/clipcc-gui#207]
### 描述一下bug
如题。
## 请叙述bug触发步骤
已登录codingclip.com的情况下，edge浏览器在新标签页里添加codingclip.com，然后直接单击访问
## 预期的行为
与之前一样，登录状态如实显示。
## ClipCC版本
社区

**Comment by NanHaiJuRuo** [comment]
以及，刷新后又会正常显示
