### ISSUE TITLE
建议建立扩展审核申请区

### ISSUE THREAD

**Issue by NanHaiJuRuo** [Clipteam/clipcc-gui#208]
### 描述一下你想要的功能
新版扩展商店现在还没有，我提个暂时性的建议啊：
用github建立扩展审核请求区，发issue请求审核扩展
### 你为什么想要实现它？（可选）
私信会很乱，而且不便于管理审核单。

**Comment by alexcui03** [comment]
等社区扩展商店 @SimonShiki @frank-782
