### ISSUE TITLE
部分scratch官方扩展不能直接在编辑器里加载

### ISSUE THREAD

**Issue by NanHaiJuRuo** [Clipteam/clipcc-gui#210]
### 描述一下bug
如题。
## 请叙述bug触发步骤
打开编辑器，扩展页面。
## 预期的行为
原版的所有扩展都能完成装载
## ClipCC版本
3.1.4
## 附加内容
这是特性吗

**Comment by SimonShiki** [comment]
请说明具体无法加载的扩展

**Comment by NanHaiJuRuo** [comment]
意思是，部分scratch原版扩展在clipcc并不能按一下开关就启用。  
![image](https://user-images.githubusercontent.com/109646559/199502499-d08e2181-ca18-4d32-9900-49dece30ceeb.png)

**Comment by SimonShiki** [comment]
> 意思是，部分scratch原版扩展在clipcc并不能按一下开关就启用。  
> ![image](https://user-images.githubusercontent.com/109646559/199502499-d08e2181-ca18-4d32-9900-49dece30ceeb.png)
> 

ClipCC 不对硬件扩展进行兼容性保证，且当前源码库并不能运行 ScratchLink。故不开放扩展开关，仅作积木兼容性保证
