### ISSUE TITLE
别针社区将代码闭源，违背 AGPL3 代码许可证

### ISSUE THREAD

**Issue by 3swordman** [Clipteam/clipcc-gui#214]
# [AGPL3 许可证](https://github.com/Clipteam/clipcc-gui/blob/master/LICENSE)中[5.c](https://github.com/Clipteam/clipcc-gui/blob/master/LICENSE#L210)条要求所有使用/修改 clipcc 的软件（包括网页）继续按照 AGPL3 开源，然而[社区版](https://doc.codingclip.com/zh-cn/community)不以 AGPL3 开源代码，违背了 AGPL3 许可证，侵犯了 clipcc 的正当权益。

**Comment by SimonShiki** [comment]
See [Contributor License Agreement](https://github.com/Clipteam/clipcc-gui/blob/master/Contributor%20License%20Agreement)
