### ISSUE TITLE
鼠标按键侦测积木会引发一系列问题

### ISSUE THREAD

**Issue by Someone-Yang** [Clipteam/clipcc-gui#23]
### 描述一下bug

鼠标按键侦测积木会引发一系列的问题。  
触发后，整个编辑器将会出现这些问题：
- 积木变形、控件错位
- 编辑区无法操作
- 部分Clip CC新增积木无法正常删除
- 控制台会报错

*仍然不清楚原生Scratch是否有这个问题，因为原版积木暂时都不会出现这个问题。我**可能**会继续在原生Scratch编辑器上继续测试，如有消息我会第一时间修改（*

## 请叙述bug触发步骤

从任意角色/舞台编辑区取出这个积木，打开下拉框设置为除left的任意选项，然后新建角色。

## 预期的行为

新角色编辑区正常清空。

## 截图或视频

[触发步骤视频](https://www.bilibili.com/video/bv1CD4y1S7qd)

## ClipCC版本

*未知/2020.07.06*

## 附加内容

**设备信息：** Windows 7 x86,chromium 78.0.3904

**Comment by Eureka0225** [comment]
可以在b202007201042上复现

**Comment by alexcui03** [comment]
fixed (clipcc-block #822e7d6)
