### ISSUE TITLE
增加get/post模块

### ISSUE THREAD

**Issue by SinanGentoo** [Clipteam/clipcc-gui#6]
如题
为保证安全性可以仅开放离线编辑器使用，线上需要提前审批后使用

**Comment by Eureka0225** [comment]
It's not a good idea.
Someone may do the bad things before check.

**Comment by SinanGentoo** [comment]
> It's not a good idea.
> Someone may do the bad things before check.

My idea is that users only use the offline version without restrictions, the online version is restricted, which is similar to the aerfaying

**Comment by Hydrostic** [comment]
From my point of view, it’s ok to add get/post extension in offline editor, but when the editor opens a project that uses external interaction extensions, it should give an alert to notify user that this project may be dangerous, then user can choose whether to disable external interaction function or enable it with limit.

**Comment by alexcui03** [comment]
> It's not a good idea.
> Someone may do the bad things before check.

Literally it is an unnecessary worry because every kinds of api all might have danger actions if anyone abuse it. So do you think `std::ofstream` with `for` statement in C++ is dangerous? Of course it can make huge numbers of files on your disk.

**Comment by Hydrostic** [comment]
And in online version, we will limit the url of the request, user can submit the api’s url that he/she wants us to enable. But these apis must be serviced by famous company or government like China Weather, but first of all, these apis’ owners must allow us to use their apis. If they don't allow it, we'll break the law.

**Comment by cxzlw** [comment]
> 题如
> 为保证安全性可以仅开放离线编辑器使用，线上需要提前审批后使用

Well，
算了不写英文了，我的建议是在线时用户白名单过滤

**Comment by SinanGentoo** [comment]
> > 题如
> > 为保证安全性可以仅开放离线编辑器使用，线上需要提前审批后使用
> 
> Well，
> 算了不写英文了，我的建议是在线时用户白名单过滤

What do you mean?

**Comment by waterblock79** [comment]
> > > 题如
> > > 为保证安全性可以直接开放离线编辑器使用，线上需要提前审批后使用
> > 
> > 
> > 好，
> > 算了不写英文了，我的建议是在线时用户白名单过滤
> 
> 你什么意思？

I think API is not unnecessary,user can do it by their own,why API?api will create risk.

**Comment by cxzlw** [comment]
。。。
我没说清楚吗
好吧，再说遍
在程序开始时：申请url（“https://www.baidu.com”，理由/作用）申请域名orIP（“baidu.com”，理由/作用）申请全互联网访问（理由/作用）
然后只有用户允许的才可以访问否则失败
用户也可以选择单步执行，当发起请求时弹出提示显示url，data，由用户审批，而不是管理

**Comment by cxzlw** [comment]
也可以加入申请并访问

**Comment by SinanGentoo** [comment]
> > > > 题如
> > > > 为保证安全性可以直接开放离线编辑器使用，线上需要提前审批后使用
> > > 
> > > 
> > > 好，
> > > 算了不写英文了，我的建议是在线时用户白名单过滤
> > 
> > 你什么意思？
> 
> I think API is not unnecessary,user can do it by theirself,why API?api will create risk.

But there are some APIs that cannot be created by Scratch, especially for online APIs

**Comment by cxzlw** [comment]
用户在自己的设置（离线：编辑器设置，在线：个人设置）可以设置全局的白名单

**Comment by cxzlw** [comment]
。。。
我没说清楚吗
好吧，再说遍
在程序开始时：申请url（“https://www.baidu.com”，理由/作用）申请域名orIP（“baidu.com”，理由/作用）申请全互联网访问（理由/作用）
然后只有用户允许的才可以访问否则失败
用户也可以选择单步执行，当发起请求时弹出提示显示url，data，由用户审批，而不是管理
程序可以调用申请并发起请求临时请求权限
用户在自己的设置（离线：编辑器设置，在线：个人设置）可以设置全局的白名单，避免审批麻烦

**Comment by cxzlw** [comment]
。。。
我没说清楚吗
好吧，再说遍
在程序开始时：申请url（“https://www.baidu.com”，理由/作用）申请域名orIP（“baidu.com”，理由/作用）申请全互联网访问（理由/作用）
然后只有用户允许的才可以访问否则失败
用户也可以选择单步执行，当发起请求时弹出提示显示url，data，由用户审批，而不是管理
程序可以调用申请并发起请求临时请求权限
用户在自己的设置（离线：编辑器设置，在线：个人设置）可以设置全局的白名单，避免审批麻烦
------------------------------------------------------------------------------------------------------------
All right, say it again At the beginning of the program: apply for URL ("HTTPS://www.baidu.com", reason/role) apply for domain name ORIP ("baidu.com", reason/role) apply for full Internet access (reason/role) Then access is only allowed by the user, otherwise it fails. The user can also choose to step into one step, and when a request is initiated, a prompt will pop up to display url, data, which will be approved by the user instead of being managed. The program can call the application and initiate a request for temporary request permission. Users can set a global white list in their own settings (offline: editor settings, online: personal settings) to avoid approval trouble.

**Comment by cxzlw** [comment]
> > > 题如
> > > 为保证安全性可以仅开放离线编辑器使用，线上需要提前审批后使用
> > 
> > 
> > Well，
> > 算了不写英文了，我的建议是在线时用户白名单过滤
> 
> What do you mean?

。。。
我没说清楚吗
好吧，再说遍
在程序开始时：申请url（“https://www.baidu.com”，理由/作用）申请域名orIP（“baidu.com”，理由/作用）申请全互联网访问（理由/作用）
然后只有用户允许的才可以访问否则失败
用户也可以选择单步执行，当发起请求时弹出提示显示url，data，由用户审批，而不是管理
程序可以调用申请并发起请求临时请求权限
用户在自己的设置（离线：编辑器设置，在线：个人设置）可以设置全局的白名单，避免审批麻烦
All right, say it again At the beginning of the program: apply for URL ("HTTPS://www.baidu.com", reason/role) apply for domain name ORIP ("baidu.com", reason/role) apply for full Internet access (reason/role) Then access is only allowed by the user, otherwise it fails. The user can also choose to step into one step, and when a request is initiated, a prompt will pop up to display url, data, which will be approved by the user instead of being managed. The program can call the application and initiate a request for temporary request permission. Users can set a global white list in their own settings (offline: editor settings, online: personal settings) to avoid approval trouble.

**Comment by SinanGentoo** [comment]
> 。。。
> 我没说清楚吗
> 好吧，再说遍
> 在程序开始时：申请url（“https://www.baidu.com”，理由/作用）申请域名orIP（“baidu.com”，理由/作用）申请全互联网访问（理由/作用）
> 然后只有用户允许的才可以访问否则失败
> 用户也可以选择单步执行，当发起请求时弹出提示显示url，data，由用户审批，而不是管理

I think it's OK on the offline version. But to be honest, Most users cannot understand the specific meaning of these requests and understand their dangers. And this may cause legal disputes.

**Comment by cxzlw** [comment]
> > 。。。
> > 我没说清楚吗好吧
> > ，再说遍
> > 在程序开始时：申请url（“ [https://www.baidu.com”，理由/作用）申请域名orIP（“ baidu.com”，理由/作用）申请全互联网访问（理由/作用）](https://www.baidu.com%E2%80%9D%EF%BC%8C%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89%E7%94%B3%E8%AF%B7%E5%9F%9F%E5%90%8DorIP%EF%BC%88%E2%80%9Cbaidu.com%E2%80%9D%EF%BC%8C%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89%E7%94%B3%E8%AF%B7%E5%85%A8%E4%BA%92%E8%81%94%E7%BD%91%E8%AE%BF%E9%97%AE%EF%BC%88%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89) 
> > 然后只有用户允许的才可以访问否则失败
> > 用户也可以选择单步执行，当发起请求时提示提示显示网址，数据，由用户批准，而不是管理
> 
> 我认为离线版本还可以。但老实说，大多数用户无法理解这些请求的具体含义，也无法理解其危害。这可能会引起法律纠纷。

所以你可以做个警告啊。。。

**Comment by SinanGentoo** [comment]
> > > 。。。
> > > 我没说清楚吗好吧
> > > ，再说遍
> > > 在程序开始时：申请url（“ [https://www.baidu.com”，理由/作用）申请域名orIP（“ baidu.com”，理由/作用）申请全互联网访问（理由/作用）](https://www.baidu.com%E2%80%9D%EF%BC%8C%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89%E7%94%B3%E8%AF%B7%E5%9F%9F%E5%90%8DorIP%EF%BC%88%E2%80%9Cbaidu.com%E2%80%9D%EF%BC%8C%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89%E7%94%B3%E8%AF%B7%E5%85%A8%E4%BA%92%E8%81%94%E7%BD%91%E8%AE%BF%E9%97%AE%EF%BC%88%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89) 
> > > 然后只有用户允许的才可以访问否则失败
> > > 用户也可以选择单步执行，当发起请求时提示提示显示网址，数据，由用户批准，而不是管理
> > 
> > 我认为离线版本还可以。但老实说，大多数用户无法理解这些请求的具体含义，也无法理解其危害。这可能会引起法律纠纷。
> 
> 所以你可以做个警告啊。。。
Read the comment again, plz

**Comment by cxzlw** [comment]
> > 。。。
> > 我没说清楚吗好吧
> > ，再说遍
> > 在程序开始时：申请url（“ [https://www.baidu.com”，理由/作用）申请域名orIP（“ baidu.com”，理由/作用）申请全互联网访问（理由/作用）](https://www.baidu.com%E2%80%9D%EF%BC%8C%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89%E7%94%B3%E8%AF%B7%E5%9F%9F%E5%90%8DorIP%EF%BC%88%E2%80%9Cbaidu.com%E2%80%9D%EF%BC%8C%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89%E7%94%B3%E8%AF%B7%E5%85%A8%E4%BA%92%E8%81%94%E7%BD%91%E8%AE%BF%E9%97%AE%EF%BC%88%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89) 
> > 然后只有用户允许的才可以访问否则失败
> > 用户也可以选择单步执行，当发起请求时提示提示显示网址，数据，由用户批准，而不是管理
> 
> 我认为离线版本还可以。但老实说，大多数用户无法理解这些请求的具体含义，也无法理解其危害。这可能会引起法律纠纷。我认为让用户做出自己的选择不是一个好主意

当访问到除管理员审批的白名单外的地址时，同意则进行二次确认，并展示用户协议，对未知风险不负责
---------------------------------------------
When an address other than the white list approved by the administrator is accessed, the consent will be confirmed for the second time, and the user agreement will be displayed, thus the user is not responsible for the unknown risks.

**Comment by SinanGentoo** [comment]
> > > 。。。
> > > 我没说清楚吗好吧
> > > ，再说遍
> > > 在程序开始时：申请url（“ [https://www.baidu.com”，理由/作用）申请域名orIP（“ baidu.com”，理由/作用）申请全互联网访问（理由/作用）](https://www.baidu.com%E2%80%9D%EF%BC%8C%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89%E7%94%B3%E8%AF%B7%E5%9F%9F%E5%90%8DorIP%EF%BC%88%E2%80%9Cbaidu.com%E2%80%9D%EF%BC%8C%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89%E7%94%B3%E8%AF%B7%E5%85%A8%E4%BA%92%E8%81%94%E7%BD%91%E8%AE%BF%E9%97%AE%EF%BC%88%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89) 
> > > 然后只有用户允许的才可以访问否则失败
> > > 用户也可以选择单步执行，当发起请求时提示提示显示网址，数据，由用户批准，而不是管理
> > 
> > 我认为离线版本还可以。但老实说，大多数用户无法理解这些请求的具体含义，也无法理解其危害。这可能会引起法律纠纷。我认为让用户做出自己的选择不是一个好主意
> 
> 当访问到除管理员审批的白名单外的地址时，同意则进行二次确认，并展示用户协议，对未知风险不负责
> ---------------------------------------------
> When an address other than the white list approved by the administrator is accessed, the consent will be confirmed for the second time, and the user agreement will be displayed, thus the user is not responsible for the unknown risks.
> 

# The law cannot fail because of a prompt

**Comment by cxzlw** [comment]
> > > > 。。。
> > > > 我没说清楚吗好吧
> > > > ，再说遍
> > > > 在程序开始时：申请url（“ [https://www.baidu.com”，理由/作用）申请域名orIP（“ baidu.com”，理由/作用）申请全互联网访问（理由/作用）](https://www.baidu.com%E2%80%9D%EF%BC%8C%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89%E7%94%B3%E8%AF%B7%E5%9F%9F%E5%90%8DorIP%EF%BC%88%E2%80%9Cbaidu.com%E2%80%9D%EF%BC%8C%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89%E7%94%B3%E8%AF%B7%E5%85%A8%E4%BA%92%E8%81%94%E7%BD%91%E8%AE%BF%E9%97%AE%EF%BC%88%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89)
> > > > 然后只有用户允许的才可以访问否则失败
> > > > 用户也可以选择单步执行，当发起请求时提示提示显示网址，数据，由用户批准，而不是管理
> > > 
> > > 
> > > 我认为离线版本还可以。但老实说，大多数用户无法理解这些请求的具体含义，也无法理解其危害。这可能会引起法律纠纷。我认为让用户做出自己的选择不是一个好主意
> > 
> > 
> > ## 当访问到除管理员审批的白名单外的地址时，同意则进行二次确认，并展示用户协议，对未知风险不负责
> > When an address other than the white list approved by the administrator is accessed, the consent will be confirmed for the second time, and the user agreement will be displayed, thus the user is not responsible for the unknown risks.
> 
> # The law cannot fail because of a prompt

是协议

**Comment by cxzlw** [comment]
易语言写病毒还不是无罪啊

**Comment by Eureka0225** [comment]
ummm------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Alex&amp;nbsp;Cui&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月14日(星期天) 晚上9:16
收件人:&nbsp;&quot;Clipteam/clipcc-gui&quot;<clipcc-gui@noreply.github.com&gt;;
抄送:&nbsp;&quot;Eureka0225&quot;<1441373096@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Clipteam/clipcc-gui] 增加get/post模块 (#6)

**Comment by Eureka0225** [comment]
> And in online version, we will limit the url of the request, user can submit the api’s url that he/she wants us to enable. But these apis must be serviced by famous company or government like China Weather, but first of all, these apis’ owners must allow us to use their apis. If they don't allow it, we'll break the law.

That's a good idea i think. If user's community level > somethings, the user will have the right to commit to admins to add some urls to seafty urls list ( ?

**Comment by Eureka0225** [comment]
> > > 。。。
> > > 我没说清楚吗好吧
> > > ，再说遍
> > > 在程序开始时：申请url（“ [https://www.baidu.com”，理由/作用）申请域名orIP（“ baidu.com”，理由/作用）申请全互联网访问（理由/作用）](https://www.baidu.com%E2%80%9D%EF%BC%8C%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89%E7%94%B3%E8%AF%B7%E5%9F%9F%E5%90%8DorIP%EF%BC%88%E2%80%9Cbaidu.com%E2%80%9D%EF%BC%8C%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89%E7%94%B3%E8%AF%B7%E5%85%A8%E4%BA%92%E8%81%94%E7%BD%91%E8%AE%BF%E9%97%AE%EF%BC%88%E7%90%86%E7%94%B1/%E4%BD%9C%E7%94%A8%EF%BC%89)
> > > 然后只有用户允许的才可以访问否则失败
> > > 用户也可以选择单步执行，当发起请求时提示提示显示网址，数据，由用户批准，而不是管理
> > 
> > 
> > 我认为离线版本还可以。但老实说，大多数用户无法理解这些请求的具体含义，也无法理解其危害。这可能会引起法律纠纷。
> 
> 所以你可以做个警告啊。。。

Warnings are often ignored, just as you never read any user agreement.

**Comment by SinanGentoo** [comment]
HTTPIO now work in progress

**Comment by SinanGentoo** [comment]
已完成
