### ISSUE TITLE
暗色模式配色问题

### ISSUE THREAD

**Issue by SinanGentoo** [Clipteam/clipcc-gui#77]
## 描述一下bug
黑暗模式下舞台右键弹出的变量更改列表文字为黑色
## 请叙述bug触发步骤
见视频
## 预期的行为
文字为白色
## 截图或视频
https://user-images.githubusercontent.com/59327348/147399054-5d554113-7920-4966-a558-cbcffbe99eca.mp4
## 附加内容
稳定版、金丝雀版均有此问题

**Comment by frank-782** [comment]
自定义积木也有同样问题
![image](https://user-images.githubusercontent.com/46376077/147407106-2ae0231e-1f44-46cf-9393-de1578d234f3.png)
