### ISSUE TITLE
无法删除变量及列表

### ISSUE THREAD

**Issue by SinanGentoo** [Clipteam/clipcc-gui#78]
### 描述一下bug
无法删除变量及列表
## 请叙述bug触发步骤
见视频
## 预期的行为
与原版一致
## 截图或视频
https://user-images.githubusercontent.com/59327348/147399346-2cc7913d-117c-4cab-bb2c-95d7c3a3bbbf.mp4
## 附加内容
仅金丝雀版有此问题，稳定版无此问题

**Comment by frank-782** [comment]
不知道是否为缓存的问题，尝试删除变量时vm会报变量不存在`Can't delete non-existent variable: k*qkZe?d53zhJsK[~63R`

**Comment by frank-782** [comment]
已经在https://github.com/Clipteam/clipcc-block/commit/b17ec128bb9095cbd17bcd06b9c6a750ef812930修复
