### ISSUE TITLE
无法修改函数名

### ISSUE THREAD

**Issue by frank-782** [Clipteam/clipcc-gui#79]
### 描述一下bug
无法修改函数名
## 请叙述bug触发步骤
无法修改函数名，
## 预期的行为
与原版一致
## 截图或视频
见下
## 附加内容
仅金丝雀版有此问题，稳定版无此问题

https://user-images.githubusercontent.com/46376077/147406469-197f7cdd-33a8-4e49-88ab-afea3ccbdcfb.mp4

**Comment by SinanGentoo** [comment]
现在仍然有这个bug吗

**Comment by frank-782** [comment]
> 现在仍然有这个bug吗

依然存在

**Comment by frank-782** [comment]
再测试了一下，应该是Toolbox未刷新导致的（复现步骤 建立个函数 重命名，此时Toolbox未修改，切换其他角色再切换回来就正常了）

**Comment by alexcui03** [comment]
测试最新 commit 是否还存在该问题

**Comment by SinanGentoo** [comment]
已测试
修改函数内容 - 正常
修改是否带返回值 - 工作区的定义积木形状未跟随改变，且返回积木无法识别其定义积木。
![Screenshot_2022-01-02-07-17-08-630_mark.via.png](https://user-images.githubusercontent.com/59327348/147862136-aafae1e9-4b6a-41c7-aae5-ac4ba61ef1b0.png)
在其他角色取消勾选全局函数 - 未跟随改变，再次切换角色后正常。

**Comment by SinanGentoo** [comment]
Fixed
