### ISSUE TITLE
判断碰到的其他角色的克隆体的造型

### ISSUE THREAD

**Issue by FxmlesXD** [Clipteam/clipcc-gui#81]
### 描述一下你想要的功能
判断碰到的其他角色的克隆体的造型
如果碰到<角色>与碰到<角色>的造型=？？？

### 你为什么想要实现它？（可选）
这样我们就可以非常非常非常轻松地实现子弹功能

**Comment by SinanGentoo** [comment]
原版能通过正常方式实现，且开销不大。故ClipCC不会将该功能放入编辑器本体中。
