### ISSUE TITLE
分割字符()以()取第()项

### ISSUE THREAD

**Issue by FxmlesXD** [Clipteam/clipcc-gui#83]
，分割字符()以()取第()项

### 你为什么想要实现它？（可选）

**Comment by FxmlesXD** [comment]
例：分割字符(英语/数学/语文)以(/)取第(2)项
返回：数学
例：分割字符(英语'数学'语文)以(')取第(3)项
返回：语文

**Comment by frank-782** [comment]
ClipCC已经有子串模块，且该功能可通过原版实现，故添加意义不大
