### ISSUE TITLE
放置“当[响度/计时器]>()”积木时，旗帜按钮变为按下样式，不管是否执行

### ISSUE THREAD

**Issue by FxmlesXD** [Clipteam/clipcc-gui#84]
### 描述一下bug
放置“当[响度/计时器]>()”积木时，旗帜按钮变为按下样式，不管是否执行
## 请叙述bug触发步骤
打开ClipCC，拖入 当[响度]>()积木
## 预期的行为
旗帜按钮变成正常，除非执行该代码
## 截图或视频
![2021-12-31_18-33](https://user-images.githubusercontent.com/79508714/147818574-52cf2631-226d-4d41-afb1-c4131d0f1b4b.png)

## ClipCC版本
3.1.0

**Comment by frank-782** [comment]
这是Scratch的特性 不是bug
