### ISSUE TITLE
新插件：文件操作插件

### ISSUE THREAD

**Issue by FxmlesXD** [Clipteam/clipcc-gui#86]
### 描述一下你想要的功能
文件操作插件，可以操作本地文件
写入文件（目录）
读取文件（目录）
取当前sb3目录
### 你为什么想要实现它？（可选）
可以让存档不依赖存档码、云变量，吧玩家存档写入到一个dat文件，旗帜运行时读入，非常轻松的实现存档功能

**Comment by frank-782** [comment]
https://github.com/Clipteam/clipcc-extension-fileio 已经有文件系统的插件了

**Comment by SinanGentoo** [comment]
请耐心等待扩展分支的合并
