### ISSUE TITLE
如果积木返回值为bool换成<>造型而不是（）

### ISSUE THREAD

**Issue by FxmlesXD** [Clipteam/clipcc-gui#87]
### 描述一下你想要的功能
如果积木返回值为bool换成<>造型而不是（）
### 你为什么想要实现它？（可选）

**Comment by SinanGentoo** [comment]
那样返回值就只能输出true/false, 不合适

**Comment by FxmlesXD** [comment]
> 

可以试试只改变贴图

**Comment by SinanGentoo** [comment]
不明白你的意思

**Comment by FxmlesXD** [comment]
> 不明白你的意思

你可以做一个判断如果返回值为bool then换成<>的贴图，如果为int换成()的贴图。

**Comment by SinanGentoo** [comment]
你直接用<(返回值)=true>不就完事了吗

**Comment by FxmlesXD** [comment]
> 你直接用<(返回值)=true>不就完事了吗

但是这样看着不是很舒适，不过也没关系。
